jscomps_manifestdir=$(libdir)/mozembedlite/components
jscomps_manifest_DATA = \
	EmbedLiteJSComponents.manifest \
	AboutRedirector.sys.mjs \
	LoginManagerPrompter.sys.mjs \
	HelperAppDialog.sys.mjs \
	EmbedPrefService.sys.mjs \
	FilePicker.js \
	ContentPermissionPrompt.sys.mjs \
	ContentPermissionManager.sys.mjs \
	EmbedLiteGlobalHelper.sys.mjs \
	EmbedLiteNetErrorChild.sys.mjs \
	EmbedLitePromptParent.sys.mjs \
	EmbedLiteSelectionParent.sys.mjs \
	EmbedLiteWebRTCChild.sys.mjs \
	EmbedLiteWebRTCParent.sys.mjs \
	EmbedLiteWebRTCProcessChild.sys.mjs \
	EmbedLiteConsoleListener.sys.mjs \
	EmbedLiteChromeManager.sys.mjs \
	EmbedLiteSearchEngine.sys.mjs \
	UserAgentOverrideHelper.sys.mjs \
	XPIDialogService.sys.mjs \
	PrivateDataManager.sys.mjs \
	EmbedliteDownloadManager.sys.mjs \
	LoginsHelper.sys.mjs \
	EmbedLiteWebrtcUI.sys.mjs \
	IntentProtocolHandler.sys.mjs \
	$(NULL)

AM_CPPFLAGS = $(DEPS_CFLAGS)
